# Makefile for CUDA Slab Allocator project
NVCC       := nvcc
NVCC_FLAGS := -std=c++14 -arch=sm_80

all: main paraTest

main: main.cu
	$(NVCC) $(NVCC_FLAGS) $< -o $@

paraTest: paraTest.cu
	$(NVCC) $(NVCC_FLAGS) $< -o $@

run: main paraTest
	./main
	./paraTest

run-main: main
	./main

run-para: paraTest
	./paraTest


clean:
	rm -f main paraTest

